// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs


Table users {
  id integer [primary key]
  username varchar(100) [not null, unique]
  
  first_name varchar(100) [not null]
  last_name varchar(100) [not null]

  email varchar(255) [unique]
  phone varchar(30) [unique]

  password_hash varchar(255)

  created_at timestamp [not null]
}


Table roles {
  id integer [primary key]
  name varchar(100) [not null]
}

Table users_roles {
  user_id integer [primary key, ref: > users.id]
  role_id integer [primary key, ref: > roles.id]
}

Table check_in_history {
  id integer [primary key]
  user_id integer [not null, ref: > users.id]
  check_in_datetime datetime
}
